### ISSUE TITLE
Display monster base stats next to ability deck.

### ISSUE THREAD

**Issue by johngro** [drakedevel/gloomycompanion#1]
It would be good to show the base stats for a mob next to its ability deck.  This way, players can know important stuff like HP and Attack power, even when no cards have been turned over yet.

It might also be good to have a either a top level config setting, or a button on the page which can be used to show/hide the stats.  Another option might be to hide the stats any time a card is shown, but I expect that would become really visually annoying over time.

**Comment by teisenbe** [comment]
Another option would be to overlay the stats on the back of the card, but that depends on whether you care about having the base stats besides HP visible once drawing has occurred.  I don't have particularly strong opinions here

**Comment by johngro** [comment]
yeah, I thought about that but decided it would be a bit ugly, so I'm trying the next-to approach at the moment.  We'll see how it goes.  It may be unworkable when it comes to stuff like boss immunities... We'll have to see.
