### ISSUE TITLE
Card flip animations should only be shown when a user flips a card.

### ISSUE THREAD

**Issue by johngro** [drakedevel/gloomycompanion#4]
In particular, the animation should not be shown when decks become un-hidden.

**Comment by johngro** [comment]
fwiw - I have a fix for this, but it is stacked on a previous CL I have out for review (#3).  Right now I'm unsure of how to send this new fix out for review without either creating a separate branch just for the fix, or merging the CL into the existing currently pending pull request (#3).

Since I'm unclear on the proper etiquette here, I'm just going to wait until the pending pull request has made progress, or until I receive explicit guidance on what the proper thing to do is in this situation.

**Comment by teisenbe** [comment]
I think ideal with the github workflow is separate branch if the changes aren't dependent.  I'm not sure how github deals with dependent patch stacks.  Looking at your changes now.  The animation one LGTM, need to dig in to the other one
